describe('HR Dashboard CTMS', () => {
    
    it('Add Candidate with Valid Details', () => {
      cy.visit('http://localhost:5173/')
      cy.get('[name="email"]').type('yoonus.a@hr.gamagerecruiters.lk')    
      cy.get('[name="password"]').type('hr123456')
      cy.get('.space-y-6 > .bg-gradient-to-r').click()

 
      cy.contains('Add Candidate').should('be.visible').click()
      cy.get('[name="firstName"]').should('be.visible').type('Jack')
      cy.wait(2000)
      cy.get('[name="lastName"]').should('be.visible').type('Michael')
      cy.wait(2000)
      cy.get('[name="email"]').should('be.visible').type('jack@gamil.com')
      cy.wait(2000)
      cy.get('[name="phone"]').should('be.visible').type('0717621250')
      cy.get(':nth-child(2) > .flex > .px-6').click()
      cy.wait(2000)
      cy.get('[name="position"]').select('Software Engineer Intern')
      cy.wait(2000)
      cy.get('#cv').selectFile('cypress/fixtures/QA Task 2.pdf')
      cy.wait(2000)
      cy.get('[name="source"]').select('LinkedIn')
      cy.wait(2000)
      cy.get('[name="notes"]').should('be.visible').type('Good Candidate')
      cy.wait(2000)
      cy.get('.space-y-8 > .bg-gradient-to-r').click()

      cy.contains('Candidate added successfully!', { timeout: 10000 }).should('be.visible')
    })

    it('Invalid Name (contain numbers)', () => {
        cy.visit('http://localhost:5173/')
        cy.get('[name="email"]').type('yoonus.a@hr.gamagerecruiters.lk')    
        cy.get('[name="password"]').type('hr123456')
        cy.get('.space-y-6 > .bg-gradient-to-r').click()
        cy.contains('Add Candidate').should('be.visible').click()

        cy.get('[name="firstName"]').should('be.visible').type('Peter123')
          cy.wait(2000)
          cy.get('[name="lastName"]').should('be.visible').type('Silva')
          cy.wait(2000)
          cy.get('[name="email"]').should('be.visible').type('peter@gamil.com')
          cy.wait(2000)
          cy.get('[name="phone"]').should('be.visible').type('0717621250')
          cy.get(':nth-child(2) > .flex > .px-6').click()
          cy.wait(2000)
          cy.get('[name="position"]').select('Software Engineer Intern')
          cy.wait(2000)
          cy.get('#cv').selectFile('cypress/fixtures/QA Task 2.pdf')
          cy.wait(2000)
          cy.get('[name="source"]').select('LinkedIn')
          cy.wait(2000)
          cy.get('[name="notes"]').should('be.visible').type('Good Candidate')
          cy.wait(2000)
          cy.get('.space-y-8 > .bg-gradient-to-r').click()
          cy.contains('Names cannot contain numbers').should('be.visible')
            

    })

    it('Invalid Email Format', () => {
        cy.visit('http://localhost:5173/')
        cy.get('[name="email"]').type('yoonus.a@hr.gamagerecruiters.lk')    
        cy.get('[name="password"]').type('hr123456')
        cy.get('.space-y-6 > .bg-gradient-to-r').click()
        cy.contains('Add Candidate').should('be.visible').click()

        cy.get('[name="firstName"]').should('be.visible').type('Peter')
          cy.wait(2000)
          cy.get('[name="lastName"]').should('be.visible').type('Silva')
          cy.wait(2000)
          cy.get('[name="email"]').should('be.visible').type('peter.com')
          cy.wait(2000)
          cy.get('[name="phone"]').should('be.visible').type('0717621250')
          cy.get(':nth-child(2) > .flex > .px-6').click()
          cy.wait(2000)
          cy.get('[name="position"]').select('Software Engineer Intern')
          cy.wait(2000)
          cy.get('#cv').selectFile('cypress/fixtures/QA Task 2.pdf')
          cy.wait(2000)
          cy.get('[name="source"]').select('LinkedIn')
          cy.wait(2000)
          cy.get('[name="notes"]').should('be.visible').type('Good Candidate')
          cy.wait(2000)
          cy.get('.space-y-8 > .bg-gradient-to-r').click()
          cy.contains('Invalid email address').should('be.visible')
            

    })

    it('Upload wrong file for CV', () => {
        cy.visit('http://localhost:5173/')
        cy.get('[name="email"]').type('yoonus.a@hr.gamagerecruiters.lk')    
        cy.get('[name="password"]').type('hr123456')
        cy.get('.space-y-6 > .bg-gradient-to-r').click()
        cy.contains('Add Candidate').should('be.visible').click()

        cy.get('[name="firstName"]').should('be.visible').type('Peter')
          cy.wait(2000)
          cy.get('[name="lastName"]').should('be.visible').type('Silva')
          cy.wait(2000)
          cy.get('[name="email"]').should('be.visible').type('peter@gmail.com')
          cy.wait(2000)
          cy.get('[name="phone"]').should('be.visible').type('0717621250')
          cy.get(':nth-child(2) > .flex > .px-6').click()
          cy.wait(2000)
          cy.get('[name="position"]').select('Software Engineer Intern')
          cy.wait(2000)
          cy.get('#cv').selectFile('cypress/fixtures/image.jpeg')
          cy.wait(2000)
          cy.get('[name="source"]').select('LinkedIn')
          cy.wait(2000)
          cy.get('[name="notes"]').should('be.visible').type('Good Candidate')
          cy.wait(2000)
          cy.get('.space-y-8 > .bg-gradient-to-r').click()
          cy.contains('Only PDF files are allowed').should('be.visible')
            

    })
  
    
})