describe('HR Dashboard CTMS', () => {
    it('HR Dashboard Navigations', () => {
      cy.visit('http://localhost:5173/')
      cy.get('[name="email"]').type('yoonus.a@hr.gamagerecruiters.lk')    
      cy.get('[name="password"]').type('hr123456')
      cy.get('.space-y-6 > .bg-gradient-to-r').click()
      cy.scrollTo('center')
      cy.contains('View All Candidates').click()
      cy.wait(3000)
      cy.contains('HR Dashboard').click()
      cy.wait(3000)
      cy.contains('View All Interviews').click()
      cy.wait(3000)
      cy.contains('HR Dashboard').click()
      cy.contains('Get started').click()
      cy.contains('HR Dashboard').click()
      cy.get('.flex.mb-6 > .flex > :nth-child(2)').click()
      cy.wait(3000)
      cy.get('.flex > :nth-child(4)').click()
      cy.wait(3000)
      
    })
    })