import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";


const ManageHR = () => {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [hrs, setHrs] = useState([]);
  const [selectedHr, setSelectedHr] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    fetchHrs();
  }, []);

  const fetchHrs = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/auth/hrs', {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
      });
      const result = await response.json();
      if (response.ok) {
        setHrs(result);
      } else {
        alert(result.message || 'Failed to fetch HRs');
      }
    } catch (error) {
      alert('An error occurred while fetching HRs');
    }
  };

  // ✅ Generate PDF Report with Company Header + Footer
  const handleGenerateReport = () => {
  try {
    const doc = new jsPDF();

    // Current date & time
    const now = new Date();
    const dateStr = now.toLocaleDateString();
    const timeStr = now.toLocaleTimeString();

    // Header
    doc.setFontSize(16);
    doc.text("Gamage Recruiters", 105, 15, { align: "center" });

    doc.setFontSize(12);
    doc.text("HR Report", 105, 25, { align: "center" });

    // Date & Time (right corner)
    doc.setFontSize(10);
    doc.text(`Date: ${dateStr}  Time: ${timeStr}`, 190, 25, { align: "right" });

    doc.line(20, 30, 190, 30);

    // Table data
    const tableColumn = ["Full Name", "Email", "Role"];
    const tableRows = hrs.map(hr => [hr.name, hr.email, hr.role]);

    // AutoTable
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 40,
      styles: { fontSize: 10 },
      headStyles: { fillColor: [0, 128, 128] },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.text(
      "Generated by Candidate Tracking Management System",
      105,
      pageHeight - 10,
      { align: "center" }
    );

    // Save PDF
    doc.save("hr_report.pdf");
  } catch (error) {
    console.error("PDF generation error:", error);
    alert("PDF generation failed. Check console for details.");
  }
};

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this HR?')) {
      try {
        const response = await fetch(`http://localhost:5000/api/auth/hrs/${id}`, {
          method: 'DELETE',
          headers: {
            'Authorization': `Bearer ${localStorage.getItem('token')}`,
          },
        });
        const result = await response.json();
        if (response.ok) {
          alert(result.message);
          fetchHrs();
        } else {
          alert(result.message || 'Failed to delete HR');
        }
      } catch (error) {
        alert('An error occurred while deleting HR');
      }
    }
  };

  const handleUpdate = (hr) => {
    setSelectedHr(hr);
    setIsModalOpen(true);
  };

  const handleSaveUpdate = async (e) => {
    e.preventDefault();
    try {
      const response = await fetch(`http://localhost:5000/api/auth/hrs/${selectedHr._id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
        body: JSON.stringify({
          name: selectedHr.name,
          email: selectedHr.email,
          password: selectedHr.password,
          role: selectedHr.role,
        }),
      });
      const result = await response.json();
      if (response.ok) {
        alert(result.message);
        setIsModalOpen(false);
        fetchHrs();
      } else {
        alert(result.message || 'Failed to update HR');
      }
    } catch (error) {
      alert('An error occurred while updating HR');
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('role');
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    navigate('/');
  };

  const navigateTo = (path) => {
    navigate(path);
  };

  const filteredHrs = hrs.filter(hr =>
    hr.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    hr.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="flex min-h-screen bg-gray-100 relative">
      {/* Main Content with Blur Effect */}
      <div className={`flex-1 flex flex-col transition-all duration-300 ${isModalOpen ? 'blur-sm' : ''}`}>
        {/* Navbar */}
        <nav className="bg-teal-600 text-white p-4 flex justify-between items-center w-full z-10">
          <h1 className="text-xl font-bold">Candidate Tracking Management System</h1>
          <div className="flex items-center">
            <span className="mr-4">Welcome, Admin</span>
          </div>
          <button onClick={handleLogout} className="bg-teal-800 px-4 py-2 rounded">Logout</button>
        </nav>

        {/* Sidebar and Main Content */}
        <div className="flex flex-1">
          <div className="w-64 bg-gray-800 text-white h-full z-10">
            <nav className="flex flex-col h-full">
              <button onClick={() => navigateTo('/admin/dashboard')} className="flex items-center p-4 hover:bg-gray-700">
                <span className="mr-2">🏠</span> Dashboard
              </button>
              <button onClick={() => navigateTo('/admin/create-hr')} className="flex items-center p-4 hover:bg-gray-700">
                <span className="mr-2">👥</span> Create HR
              </button>
              <button onClick={() => navigateTo('/admin/manage-hr')} className="flex items-center p-4 bg-blue-600 hover:bg-blue-600">
                <span className="mr-2">📊</span> Manage HR
              </button>
              <button onClick={() => navigateTo('/admin/view-interviews')} className="flex items-center p-4 hover:bg-gray-700">
                <span className="mr-2">👁️</span> View Interviews
              </button>
            </nav>
          </div>

          {/* Main Content Area */}
          <div className="flex-1 p-6">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold text-center text-gray-800">Manage HR</h2>
              
              {/* Search Bar and Generate Report */}
              <div className="flex items-center space-x-4">
                <div className="flex-1 relative">
                  <input
                    type="text"
                    placeholder="Search HR by name or email..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500"
                  />
                  <span className="absolute left-3 top-2.5 text-gray-400">🔍</span>
                </div>
                <button
                  onClick={handleGenerateReport}
                  className="bg-teal-600 text-white px-6 py-2 rounded-lg hover:bg-teal-700 focus:ring-2 focus:ring-teal-500 transition duration-200"
                >
                  Generate Report
                </button>
              </div>

              {/* HR Table */}
              <div className="mt-6">
                <table className="w-full bg-white border border-gray-200 rounded-lg shadow-sm">
                  <thead>
                    <tr className="bg-gray-100 text-gray-700">
                      <th className="p-3 text-left">Full Name</th>
                      <th className="p-3 text-left">Email</th>
                      <th className="p-3 text-left">Role</th>
                      <th className="p-3 text-left">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredHrs.map((hr) => (
                      <tr key={hr._id} className="border-t">
                        <td className="p-3">{hr.name}</td>
                        <td className="p-3">{hr.email}</td>
                        <td className="p-3">{hr.role}</td>
                        <td className="p-3">
                          <button
                            onClick={() => handleUpdate(hr)}
                            className="text-blue-600 hover:text-blue-900 px-2 py-1 rounded"
                          >
                            ✏️ Edit
                          </button>
                          <button
                            onClick={() => handleDelete(hr._id)}
                            className="text-red-600 hover:text-red-900 px-2 py-1 rounded"
                          >
                           🗑️ Delete
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Update Modal */}
      {isModalOpen && selectedHr && (
        <div className="fixed inset-0 flex items-center justify-center z-50">
          <div className="bg-white p-6 rounded-lg shadow-lg w-96">
            <h3 className="text-xl font-bold text-teal-700 mb-4">Update HR</h3>
            <form onSubmit={handleSaveUpdate} className="space-y-4">
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-name">
                  Full Name
                </label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500"
                  id="update-name"
                  type="text"
                  value={selectedHr.name}
                  onChange={(e) => setSelectedHr({ ...selectedHr, name: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-email">
                  Email
                </label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500"
                  id="update-email"
                  type="email"
                  value={selectedHr.email}
                  onChange={(e) => setSelectedHr({ ...selectedHr, email: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-password">
                  Password
                </label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500"
                  id="update-password"
                  type="password"
                  value={selectedHr.password || ''}
                  onChange={(e) => setSelectedHr({ ...selectedHr, password: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-role">
                  Role
                </label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500"
                  id="update-role"
                  type="text"
                  value={selectedHr.role}
                  onChange={(e) => setSelectedHr({ ...selectedHr, role: e.target.value })}
                />
              </div>
              <div className="flex justify-end space-x-4">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="bg-gray-500 text-white px-4 py-2 rounded-lg hover:bg-gray-600"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="bg-teal-600 text-white px-4 py-2 rounded-lg hover:bg-teal-700"
                >
                  Save
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default ManageHR;
