import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { motion } from 'framer-motion';
import { FiHome, FiUserPlus, FiUsers, FiEye, FiLogOut } from 'react-icons/fi';

const ManageHR = () => {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [hrs, setHrs] = useState([]);
  const [selectedHr, setSelectedHr] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    fetchHrs();
  }, []);

  const fetchHrs = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/auth/hrs', {
        headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` },
      });
      const result = await response.json();
      if (response.ok) setHrs(result);
      else alert(result.message || 'Failed to fetch HRs');
    } catch (error) {
      alert('An error occurred while fetching HRs');
    }
  };

  const handleGenerateReport = () => {
    try {
      const doc = new jsPDF();
      const now = new Date();
      const dateStr = now.toLocaleDateString();
      const timeStr = now.toLocaleTimeString();

      doc.setFontSize(16);
      doc.text("Gamage Recruiters", 105, 15, { align: "center" });
      doc.setFontSize(12);
      doc.text("HR Report", 105, 25, { align: "center" });
      doc.setFontSize(10);
      doc.text(`Date: ${dateStr}  Time: ${timeStr}`, 190, 25, { align: "right" });
      doc.line(20, 30, 190, 30);

      const tableColumn = ["Full Name", "Email", "Role"];
      const tableRows = hrs.map(hr => [hr.name, hr.email, hr.role]);

      autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 40,
        styles: { fontSize: 10 },
        headStyles: { fillColor: [0, 128, 128] },
      });

      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(10);
      doc.text("Generated by Candidate Tracking Management System", 105, pageHeight - 10, { align: "center" });
      doc.save("hr_report.pdf");
    } catch (error) {
      console.error("PDF generation error:", error);
      alert("PDF generation failed. Check console for details.");
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this HR?')) {
      try {
        const response = await fetch(`http://localhost:5000/api/auth/hrs/${id}`, {
          method: 'DELETE',
          headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` },
        });
        const result = await response.json();
        if (response.ok) {
          alert(result.message);
          fetchHrs();
        } else alert(result.message || 'Failed to delete HR');
      } catch (error) {
        alert('An error occurred while deleting HR');
      }
    }
  };

  const handleUpdate = (hr) => {
    setSelectedHr(hr);
    setIsModalOpen(true);
  };

  const handleSaveUpdate = async (e) => {
    e.preventDefault();
    try {
      const response = await fetch(`http://localhost:5000/api/auth/hrs/${selectedHr._id}`, {
        method: 'PUT',
        headers: { 
          'Content-Type': 'application/json', 
          'Authorization': `Bearer ${localStorage.getItem('token')}` 
        },
        body: JSON.stringify({ 
          name: selectedHr.name, 
          email: selectedHr.email, 
          password: selectedHr.password, 
          role: selectedHr.role 
        }),
      });
      const result = await response.json();
      if (response.ok) {
        alert(result.message);
        setIsModalOpen(false);
        fetchHrs();
      } else alert(result.message || 'Failed to update HR');
    } catch (error) {
      alert('An error occurred while updating HR');
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('role');
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    navigate('/');
  };

  const navigateTo = (path) => {
    navigate(path);
  };

  const filteredHrs = hrs.filter(hr =>
    hr.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    hr.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const containerVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6, staggerChildren: 0.2 } },
  };

  const itemVariants = {
    hidden: { opacity: 0, scale: 0.9 },
    visible: { opacity: 1, scale: 1, transition: { duration: 0.4 } },
  };

  return (
    <div className="flex min-h-screen bg-gray-100 font-sans relative">
      <div className="flex-1 flex flex-col transition-all duration-300">
        {/* Navbar */}
        <nav className="bg-gradient-to-r from-teal-800 to-blue-900 text-white p-6 flex justify-between items-center shadow-lg backdrop-blur-md">
          <div className="flex items-center">
            <h1 className="text-2xl font-bold mr-6 bg-gradient-to-r text-white bg-clip-text text-transparent">Candidate Tracking System</h1>
            
          </div>
          <div className="flex items-center">
            <span className="mr-6 text-md  font-medium">Welcome, Admin</span>
            <motion.button
              whileHover={{ scale: 1.05, backgroundColor: '#1e40af' }}
              whileTap={{ scale: 0.95 }}
              onClick={handleLogout}
              className="flex items-center bg-blue-800 text-white px-5 py-2 rounded-xl hover:bg-blue-700 transition duration-300 shadow-md"
            >
              <FiLogOut className="mr-2" /> Logout
            </motion.button>
          </div>
        </nav>

        <div className="flex flex-1">
          {/* Sidebar */}
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: 256 }}
            transition={{ duration: 0.5 }}
            className="bg-gray-800 text-white h-full shadow-lg min-w-[256px]"
          >
            <nav className="flex flex-col h-full p-6">
              <motion.button
                whileHover={{ scale: 1.05, backgroundColor: '#2563eb', color: '#ffffff' }}
                whileTap={{ scale: 0.95 }}
                onClick={() => navigateTo('/admin/dashboard')}
                className="flex items-center p-3 mb-4 bg-gray-700/80 text-white rounded-xl hover:bg-gray-600 transition duration-200 shadow-md"
              >
                <FiHome className="mr-3 text-lg" /> Dashboard
              </motion.button>
              <motion.button
                whileHover={{ scale: 1.05, backgroundColor: '#2563eb', color: '#ffffff' }}
                whileTap={{ scale: 0.95 }}
                onClick={() => navigateTo('/admin/create-hr')}
                className="flex items-center p-3 mb-4 bg-gray-700/80 text-white rounded-xl hover:bg-gray-600 transition duration-200 shadow-md"
              >
                <FiUserPlus className="mr-3 text-lg" /> Create HR
              </motion.button>
              <motion.button
                whileHover={{ scale: 1.05, backgroundColor: '#2563eb', color: '#ffffff' }}
                whileTap={{ scale: 0.95 }}
                onClick={() => navigateTo('/admin/manage-hr')}
                className="flex items-center p-3 mb-4 bg-blue-600/80 text-white rounded-xl hover:bg-blue-700 transition duration-200 shadow-md"
              >
                <FiUsers className="mr-3 text-lg" /> Manage HR
              </motion.button>
              <motion.button
                whileHover={{ scale: 1.05, backgroundColor: '#2563eb', color: '#ffffff' }}
                whileTap={{ scale: 0.95 }}
                onClick={() => navigateTo('/admin/view-interviews')}
                className="flex items-center p-3 mb-4 bg-gray-700/80 text-white rounded-xl hover:bg-gray-600 transition duration-200 shadow-md"
              >
                <FiEye className="mr-3 text-lg" /> View Interviews
              </motion.button>
            </nav>
          </motion.div>

          {/* Content */}
          <div className="flex-1 p-8 overflow-auto bg-gradient-to-br from-gray-50 to-teal-50">
            <motion.div initial="hidden" animate="visible" variants={containerVariants} className="space-y-8">
              <h2 className="text-3xl font-bold text-teal-700 text-center bg-gradient-to-r from-teal-600 to-blue-600 bg-clip-text text-transparent">Manage HR</h2>
              <div className="flex items-center space-x-6">
                <motion.div variants={itemVariants} className="flex-1 relative">
                  <input
                    type="text"
                    placeholder="Search HR by name or email..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full pl-10 pr-4 py-3 border-0 rounded-xl bg-white/80 backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-teal-500 shadow-lg"
                  />
                  <span className="absolute left-3 top-3.5 text-gray-500">🔍</span>
                </motion.div>
                <motion.button 
                  whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
                  onClick={handleGenerateReport}
                  className="bg-gradient-to-r from-teal-600 to-blue-600 text-white px-6 py-3 rounded-xl hover:from-teal-700 hover:to-blue-700 focus:ring-2 focus:ring-gold-500 transition duration-300 font-semibold"
                >
                  Generate Report
                </motion.button>
              </div>

              <motion.div variants={itemVariants} className="mt-8">
                <div className="bg-white rounded-xl shadow-xl overflow-hidden">
                  <table className="w-full divide-y divide-gray-200">
                    <thead className="bg-gradient-to-r from-teal-100 to-blue-100">
                      <tr>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Full Name</th>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Email</th>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Role</th>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-100">
                      {filteredHrs.map((hr) => (
                        <motion.tr key={hr._id} variants={itemVariants} className="hover:bg-teal-50 transition duration-200">
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-700">{hr.name}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{hr.email}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{hr.role}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm">
                            <motion.button 
                              whileHover={{ scale: 1.1, color: '#2563eb' }} whileTap={{ scale: 0.95 }}
                              onClick={() => handleUpdate(hr)}
                              className="text-blue-600 hover:text-blue-800 mr-4"
                            >
                              ✏️ Edit
                            </motion.button>
                            <motion.button 
                              whileHover={{ scale: 1.1, color: '#dc2626' }} whileTap={{ scale: 0.95 }}
                              onClick={() => handleDelete(hr._id)}
                              className="text-red-600 hover:text-red-800"
                            >
                              🗑️ Delete
                            </motion.button>
                          </td>
                        </motion.tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </motion.div>
            </motion.div>
          </div>
        </div>
      </div>

      {/* Popup Form */}
      {isModalOpen && selectedHr && (
        <div
          className="fixed inset-0 flex items-center justify-center z-50"
          style={{
            backgroundColor: "rgba(0,0,0,0.2)",
            backdropFilter: "blur(2px)",
          }}
        >
          <motion.div 
            initial={{ opacity: 0, y: 50 }} 
            animate={{ opacity: 1, y: 0 }} 
            exit={{ opacity: 0, y: 50 }}
            className="bg-white p-6 rounded-2xl shadow-2xl w-96 z-50 border border-gray-200"
          >
            <div className="bg-gradient-to-r from-teal-600 to-blue-600 rounded-t-xl p-4 mb-6">
              <h3 className="text-xl font-bold text-white">Update HR</h3>
            </div>
            <form onSubmit={handleSaveUpdate} className="space-y-6">
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-name">Full Name</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 transition duration-200"
                  id="update-name"
                  type="text"
                  value={selectedHr.name}
                  onChange={(e) => setSelectedHr({ ...selectedHr, name: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-email">Email</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 transition duration-200"
                  id="update-email"
                  type="email"
                  value={selectedHr.email}
                  onChange={(e) => setSelectedHr({ ...selectedHr, email: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-password">Password</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 transition duration-200"
                  id="update-password"
                  type="password"
                  value={selectedHr.password || ''}
                  onChange={(e) => setSelectedHr({ ...selectedHr, password: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-role">Role</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 transition duration-200"
                  id="update-role"
                  type="text"
                  value={selectedHr.role}
                  onChange={(e) => setSelectedHr({ ...selectedHr, role: e.target.value })}
                />
              </div>
              <div className="flex justify-end space-x-6">
                <motion.button 
                  whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
                  type="button" 
                  onClick={() => setIsModalOpen(false)}
                  className="bg-gray-500 text-white px-4 py-2 rounded-lg hover:bg-gray-600 transition duration-200"
                >
                  Cancel
                </motion.button>
                <motion.button 
                  whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
                  type="submit" 
                  className="bg-gradient-to-r from-teal-600 to-blue-600 text-white px-4 py-2 rounded-lg hover:from-teal-700 hover:to-blue-700 transition duration-200"
                >
                  Save
                </motion.button>
              </div>
            </form>
          </motion.div>
        </div>
      )}
    </div>
  );
};

export default ManageHR;