/* eslint-disable no-unused-vars */
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { motion } from 'framer-motion';
import { FiHome, FiUserPlus, FiUsers, FiEye, FiLogOut } from 'react-icons/fi';

const ManageHR = () => {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [hrs, setHrs] = useState([]);
  const [selectedHr, setSelectedHr] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    fetchHrs();
  }, []);

  const fetchHrs = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/auth/hrs', {
        headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` },
      });
      const result = await response.json();
      if (response.ok) setHrs(result);
      else alert(result.message || 'Failed to fetch HRs');
    } catch (error) {
      alert('An error occurred while fetching HRs');
    }
  };

  const handleGenerateReport = () => {
    try {
      const doc = new jsPDF();
      
      // Get current date and time
      const now = new Date();
      const dateStr = now.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: '2-digit', 
        day: '2-digit' 
      });
      const timeStr = now.toLocaleTimeString('en-US', { 
        hour: '2-digit', 
        minute: '2-digit', 
        second: '2-digit',
        hour12: true 
      });
      
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Add Company Logo
      const logoImg = new Image();
      logoImg.src = '/GR.jpg'; // Your company logo path
      
      // Add logo on the left side
      try {
        doc.addImage(logoImg, 'JPEG', 14, 10, 20, 20);
      } catch (error) {
        console.log('Logo not loaded, continuing without logo');
      }
      
      // Company Name - Next to logo
      doc.setFontSize(20);
      doc.setFont(undefined, 'bold');
      doc.text('Gamage Recruiters', 40, 20);
      
      // Report Title and Date
      doc.setFontSize(12);
      doc.setFont(undefined, 'normal');
      const reportTitle = 'HR Report';
      const dateTime = `Date: ${dateStr} Time: ${timeStr}`;
      
      // Calculate positions for left-aligned title and right-aligned date
      const titleX = 40;
      const dateX = pageWidth - 14;
      
      doc.text(reportTitle, titleX, 28);
      doc.text(dateTime, dateX, 28, { align: 'right' });
      
      // Line separator
      doc.setLineWidth(0.5);
      doc.line(14, 35, pageWidth - 14, 35);

      const tableColumn = ["Full Name", "Email", "Role"];
      const tableRows = hrs.map(hr => [hr.name, hr.email, hr.role]);

      autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 40,
        theme: 'grid',
        headStyles: {
          fillColor: [3, 98, 76],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          halign: 'center'
        },
        styles: {
          fontSize: 10,
          cellPadding: 3,
          overflow: 'linebreak'
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245]
        }
      });

      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(10);
      doc.text("Generated by Candidate Tracking Management System", 105, pageHeight - 10, { align: "center" });
      doc.save(`hr-report-${dateStr.replace(/\//g, '-')}.pdf`);
    } catch (error) {
      console.error("PDF generation error:", error);
      alert("PDF generation failed. Check console for details.");
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this HR?')) {
      try {
        const response = await fetch(`http://localhost:5000/api/auth/hrs/${id}`, {
          method: 'DELETE',
          headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` },
        });
        const result = await response.json();
        if (response.ok) {
          alert(result.message);
          fetchHrs();
        } else alert(result.message || 'Failed to delete HR');
      } catch (error) {
        alert('An error occurred while deleting HR');
      }
    }
  };

  const handleUpdate = (hr) => {
    setSelectedHr(hr);
    setIsModalOpen(true);
  };

  const handleSaveUpdate = async (e) => {
    e.preventDefault();
    try {
      const response = await fetch(`http://localhost:5000/api/auth/hrs/${selectedHr._id}`, {
        method: 'PUT',
        headers: { 
          'Content-Type': 'application/json', 
          'Authorization': `Bearer ${localStorage.getItem('token')}` 
        },
        body: JSON.stringify({ 
          name: selectedHr.name, 
          email: selectedHr.email, 
          password: selectedHr.password, 
          role: selectedHr.role 
        }),
      });
      const result = await response.json();
      if (response.ok) {
        alert(result.message);
        setIsModalOpen(false);
        fetchHrs();
      } else alert(result.message || 'Failed to update HR');
    } catch (error) {
      alert('An error occurred while updating HR');
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('role');
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    navigate('/');
  };

  const navigateTo = (path) => {
    navigate(path);
  };

  const filteredHrs = hrs.filter(hr =>
    hr.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    hr.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const containerVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6, staggerChildren: 0.2 } },
  };

  const itemVariants = {
    hidden: { opacity: 0, scale: 0.9 },
    visible: { opacity: 1, scale: 1, transition: { duration: 0.4 } },
  };

  return (
    <div className="flex min-h-screen bg-gradient-to-br from-[#03624c] via-[#030f0f] to-[#00df82] font-sans relative">
      <div className="flex-1 flex flex-col transition-all duration-300">
        {/* Navbar */}
        <motion.nav 
          initial={{ y: -100 }}
          animate={{ y: 0 }}
          className="bg-gradient-to-r from-[#03624c] to-[#030f0f] text-white p-4 flex justify-between items-center w-full shadow-lg"
        >
          <div className="flex items-center">
            <motion.img
              src="/GR.jpg"
              alt="Company Logo"
              transition={{ duration: 0.5 }}
              className="w-10 h-10 mr-3 object-contain"
            />
            <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-[#00df82]">
              Candidate Tracking System
            </h1>
          </div>
          <div className="flex items-center space-x-4">
            <motion.div
              whileHover={{ scale: 1.05 }}
              className="bg-[#03624c] px-4 py-2 rounded-full shadow-lg"
            >
              <span className="font-medium">Welcome, Admin</span>
            </motion.div>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleLogout}
              className="bg-red-500 px-6 py-2 rounded-full hover:bg-red-600 shadow-lg font-medium flex items-center justify-center"
            >
              <FiLogOut className="mr-2" /> Logout
            </motion.button>
          </div>
        </motion.nav>

        <div className="flex flex-1">
          {/* Sidebar */}
          <motion.div 
            initial={{ x: -300 }}
            animate={{ x: 0 }}
            transition={{ type: "spring", stiffness: 100 }}
            className="w-64 bg-gradient-to-b from-[#030f0f] to-[#03624c] text-white h-full shadow-2xl"
          >
            <nav className="flex flex-col h-full py-6">
              <motion.button
                whileHover={{ x: 10, scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => navigateTo('/admin/dashboard')}
                className="flex items-center p-4 mx-2 rounded-lg mb-1 transition-all duration-200 hover:bg-[rgba(0,223,130,0.1)] hover:bg-opacity-10"
              >
                <FiHome className="mr-3 text-lg" /> Dashboard
              </motion.button>
              <motion.button
                whileHover={{ x: 10, scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => navigateTo('/admin/create-hr')}
                className="flex items-center p-4 mx-2 rounded-lg mb-1 transition-all duration-200 hover:bg-[rgba(0,223,130,0.1)] hover:bg-opacity-10"
              >
                <FiUserPlus className="mr-3 text-lg" /> Create HR
              </motion.button>
              <motion.button
                whileHover={{ x: 10, scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => navigateTo('/admin/manage-hr')}
                className="flex items-center p-4 mx-2 rounded-lg mb-1 transition-all duration-200 bg-gradient-to-r from-[#03624c] to-[#030f0f]"
              >
                <FiUsers className="mr-3 text-lg" /> Manage HR
              </motion.button>
              <motion.button
                whileHover={{ x: 10, scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => navigateTo('/admin/view-interviews')}
                className="flex items-center p-4 mx-2 rounded-lg mb-1 transition-all duration-200 hover:bg-[rgba(0,223,130,0.1)] hover:bg-opacity-10"
              >
                <FiEye className="mr-3 text-lg" /> View Interviews
              </motion.button>
              <motion.button
                whileHover={{ x: 10, scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => navigateTo('/admin/manage-candidate')}
                className="flex items-center p-4 mx-2 rounded-lg mb-1 transition-all duration-200 hover:bg-[rgba(0,223,130,0.1)] hover:bg-opacity-10"
              >
                <FiUsers className="mr-3 text-lg" /> Manage Candidates
              </motion.button>
            </nav>
          </motion.div>

          {/* Content */}
          <div className="flex-1 p-8 overflow-auto bg-gradient-to-br from-[#03624c]/10 to-[#00df82]/10">
            <motion.div initial="hidden" animate="visible" variants={containerVariants} className="space-y-8">
              <h2 className="text-3xl font-bold text-white text-center bg-gradient-to-r from-[#03624c] to-[#030f0f] bg-clip-text text-transparent">Manage HR</h2>
              <div className="flex items-center space-x-6">
                <motion.div variants={itemVariants} className="flex-1 relative">
                  <input
                    type="text"
                    placeholder="Search HR by name or email..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full pl-10 pr-4 py-3 border-0 rounded-xl bg-white/80 backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-[#00df82] shadow-lg"
                  />
                  <span className="absolute left-3 top-3.5 text-gray-500">🔍</span>
                </motion.div>
                <motion.button 
                  whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
                  onClick={handleGenerateReport}
                  className="bg-gradient-to-r from-[#03624c] to-[#030f0f] text-white px-6 py-3 rounded-xl hover:from-[#00df82] hover:to-[#03624c] focus:ring-2 focus:ring-[#00df82]/50 transition duration-300 font-semibold"
                >
                  Generate Report
                </motion.button>
              </div>

              <motion.div variants={itemVariants} className="mt-8">
                <div className="bg-white rounded-xl shadow-xl overflow-hidden">
                  <table className="w-full divide-y divide-gray-200">
                    <thead className="bg-gradient-to-r from-[#03624c]/50 to-[#030f0f]/50">
                      <tr>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Full Name</th>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Email</th>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Role</th>
                        <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-100">
                      {filteredHrs.map((hr) => (
                        <motion.tr key={hr._id} variants={itemVariants} className="hover:bg-[#00df82]/10 transition duration-200">
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-700">{hr.name}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{hr.email}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{hr.role}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm">
                            <motion.button 
                              whileHover={{ scale: 1.1, color: '#00df82' }} whileTap={{ scale: 0.95 }}
                              onClick={() => handleUpdate(hr)}
                              className="text-[#03624c] hover:text-[#00df82] mr-4"
                            >
                              ✏️ Edit
                            </motion.button>
                            <motion.button 
                              whileHover={{ scale: 1.1, color: '#dc2626' }} whileTap={{ scale: 0.95 }}
                              onClick={() => handleDelete(hr._id)}
                              className="text-red-600 hover:text-red-800"
                            >
                              🗑️ Delete
                            </motion.button>
                          </td>
                        </motion.tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </motion.div>
            </motion.div>
          </div>
        </div>
      </div>

      {/* Popup Form */}
      {isModalOpen && selectedHr && (
        <div
          className="fixed inset-0 flex items-center justify-center z-50"
          style={{
            backgroundColor: "rgba(0,0,0,0.2)",
            backdropFilter: "blur(2px)",
          }}
        >
          <motion.div 
            initial={{ opacity: 0, y: 50 }} 
            animate={{ opacity: 1, y: 0 }} 
            exit={{ opacity: 0, y: 50 }}
            className="bg-white p-6 rounded-2xl shadow-2xl w-96 z-50 border border-gray-200"
          >
            <div className="bg-gradient-to-r from-[#03624c] to-[#030f0f] rounded-t-xl p-4 mb-6">
              <h3 className="text-xl font-bold text-white">Update HR</h3>
            </div>
            <form onSubmit={handleSaveUpdate} className="space-y-6">
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-name">Full Name</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#00df82] transition duration-200"
                  id="update-name"
                  type="text"
                  value={selectedHr.name}
                  onChange={(e) => setSelectedHr({ ...selectedHr, name: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-email">Email</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#00df82] transition duration-200"
                  id="update-email"
                  type="email"
                  value={selectedHr.email}
                  onChange={(e) => setSelectedHr({ ...selectedHr, email: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-password">Password</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#00df82] transition duration-200"
                  id="update-password"
                  type="password"
                  value={selectedHr.password || ''}
                  onChange={(e) => setSelectedHr({ ...selectedHr, password: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-gray-700 text-sm font-semibold mb-2" htmlFor="update-role">Role</label>
                <input
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#00df82] transition duration-200"
                  id="update-role"
                  type="text"
                  value={selectedHr.role}
                  onChange={(e) => setSelectedHr({ ...selectedHr, role: e.target.value })}
                />
              </div>
              <div className="flex justify-end space-x-6">
                <motion.button 
                  whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
                  type="button" 
                  onClick={() => setIsModalOpen(false)}
                  className="bg-gray-500 text-white px-4 py-2 rounded-lg hover:bg-gray-600 transition duration-200"
                >
                  Cancel
                </motion.button>
                <motion.button 
                  whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
                  type="submit" 
                  className="bg-gradient-to-r from-[#03624c] to-[#030f0f] text-white px-4 py-2 rounded-lg hover:from-[#00df82] hover:to-[#03624c] transition duration-200"
                >
                  Save
                </motion.button>
              </div>
            </form>
          </motion.div>
        </div>
      )}
    </div>
  );
};

export default ManageHR;